In [2]:
import pandas as pd

In [4]:
df = pd.read_excel("C:\\Users\\ROG\\Downloads\\bhel_dataset.xlsx")

In [5]:
df.head()

,COMPLAINT_NO,COMPLAINT_DATE,ID_NO,FAULTY_EQUIPMENT,PROBLEM_TYPE,PROBLEM_DESCRIPTION,NAME_OF_EQUIPMENT,EQUIPMENT_MAKE,SERVICE_COMPANY,ASSIGN_DATE,RESPONSE_DATE,RESPONSE_DESCRIPTION,SERVICE_DATE,REMEDY_DESCRIPTION,SOLVED_PROBLEM_TYPE
0,183217,2015-12-30 16:58:57,20151566.0,PC,Does not start,pc not lofin trust error show,HIGHER RAM HP PC,NaN,WIPRO,NaN,2015-12-30 16:59:33,NaN,2015-12-30 16:59:33,currupt profile reset,OTHER
1,183216,2015-12-30 16:54:48,20150737.0,PRINTER,Other - Please Specify,Printer off line,PC GEN,NaN,WIPRO,NaN,2015-12-30 16:55:46,NaN,2015-12-30 16:55:46,Changed setting,OTHER
2,183215,2015-12-30 16:53:41,20151055.0,PC,Does not start,new pc configration and domain add,PC GEN,NaN,WIPRO,NaN,2015-12-30 16:54:07,NaN,2015-12-30 16:54:07,config properly,OTHER
3,183214,2015-12-30 16:53:20,20150735.0,PRINTER,Other - Please Specify,Printer off line,PC GEN,NaN,WIPRO,NaN,2015-12-30 16:54:09,NaN,2015-12-30 16:54:09,Resolved issue,OTHER
4,183213,2015-12-30 16:51:35,20150329.0,PC,Other - Please Specify,.lst file not open,PC GEN,NaN,WIPRO,NaN,2015-12-30 16:52:26,NaN,2015-12-30 16:52:26,Changed setting,OTHER

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
df.shape     #102564 rows and 15 columns

(102564, 15)

In [8]:
df.columns

Index(['COMPLAINT_NO', 'COMPLAINT_DATE', 'ID_NO', 'FAULTY_EQUIPMENT',
       'PROBLEM_TYPE', 'PROBLEM_DESCRIPTION', 'NAME_OF_EQUIPMENT',
       'EQUIPMENT_MAKE', 'SERVICE_COMPANY', 'ASSIGN_DATE', 'RESPONSE_DATE',
       'RESPONSE_DESCRIPTION', 'SERVICE_DATE', 'REMEDY_DESCRIPTION',
       'SOLVED_PROBLEM_TYPE'],
      dtype='object')

In [9]:
df.dtypes

COMPLAINT_NO                     int64
COMPLAINT_DATE          datetime64[ns]
ID_NO                          float64
FAULTY_EQUIPMENT                object
PROBLEM_TYPE                    object
PROBLEM_DESCRIPTION             object
NAME_OF_EQUIPMENT               object
EQUIPMENT_MAKE                  object
SERVICE_COMPANY                 object
ASSIGN_DATE                    float64
RESPONSE_DATE           datetime64[ns]
RESPONSE_DESCRIPTION           float64
SERVICE_DATE            datetime64[ns]
REMEDY_DESCRIPTION              object
SOLVED_PROBLEM_TYPE             object
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102564 entries, 0 to 102563
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   COMPLAINT_NO          102564 non-null  int64
 1   COMPLAINT_DATE        102564 non-null  datetime64[ns]
 2   ID_NO                 100983 non-null  float64
 3   FAULTY_EQUIPMENT      49628 non-null   object
 4   PROBLEM_TYPE          49628 non-null   object
 5   PROBLEM_DESCRIPTION   98903 non-null   object
 6   NAME_OF_EQUIPMENT     90632 non-null   object
 7   EQUIPMENT_MAKE        45643 non-null   object
 8   SERVICE_COMPANY       102560 non-null  object
 9   ASSIGN_DATE           0 non-null       float64
 10  RESPONSE_DATE         89917 non-null   datetime64[ns]
 11  RESPONSE_DESCRIPTION  0 non-null       float64
 12  SERVICE_DATE          98774 non-null   datetime64[ns]
 13  REMEDY_DESCRIPTION    98116 non-null   object
 14  SOLVED_PROBLEM_TYPE   65739 non-null   object
dtypes: datetime64[ns](3), float64(3), int64(1), object(8)
memory usage: 11.7+ MB

In [12]:
df.isnull()        #will check every cell if the value is nul or not

,COMPLAINT_NO,COMPLAINT_DATE,ID_NO,FAULTY_EQUIPMENT,PROBLEM_TYPE,PROBLEM_DESCRIPTION,NAME_OF_EQUIPMENT,EQUIPMENT_MAKE,SERVICE_COMPANY,ASSIGN_DATE,RESPONSE_DATE,RESPONSE_DESCRIPTION,SERVICE_DATE,REMEDY_DESCRIPTION,SOLVED_PROBLEM_TYPE
0,False,False,False,False,False,False,False,True,False,True,False,True,False,False,False
1,False,False,False,False,False,False,False,True,False,True,False,True,False,False,False
2,False,False,False,False,False,False,False,True,False,True,False,True,False,False,False
3,False,False,False,False,False,False,False,True,False,True,False,True,False,False,False
4,False,False,False,False,False,False,False,True,False,True,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102559,False,False,False,True,True,False,False,False,False,True,False,True,False,False,True
102560,False,False,False,True,True,False,False,False,False,True,False,True,False,False,True
102561,False,False,False,True,True,False,False,False,False,True,False,True,False,False,True
102562,False,False,False,True,True,False,False,False,False,True,False,True,False,False,True
102563,False,False,False,True,True,False,False,False,False,True,False,True,False,False,True

In [13]:
df.isnull().sum()         #total number of null values in each column

COMPLAINT_NO                 0
COMPLAINT_DATE               0
ID_NO                     1581
FAULTY_EQUIPMENT         52936
PROBLEM_TYPE             52936
PROBLEM_DESCRIPTION       3661
NAME_OF_EQUIPMENT        11932
EQUIPMENT_MAKE           56921
SERVICE_COMPANY              4
ASSIGN_DATE             102564
RESPONSE_DATE            12647
RESPONSE_DESCRIPTION    102564
SERVICE_DATE              3790
REMEDY_DESCRIPTION        4448
SOLVED_PROBLEM_TYPE      36825
dtype: int64

In [15]:
df2 = df.fillna({'FAULTY_EQUIPMENT':'OTHER',
                'PROBLEM_TYPE':'Other - Please specify',
                'NAME_OF_EQUIPMENT':'OTHERS',
                'EQUIPMENT_MAKE':'OTHERS',
                'SERVICE_COMPANY':'OTHERS'})

In [16]:
df2

,COMPLAINT_NO,COMPLAINT_DATE,ID_NO,FAULTY_EQUIPMENT,PROBLEM_TYPE,PROBLEM_DESCRIPTION,NAME_OF_EQUIPMENT,EQUIPMENT_MAKE,SERVICE_COMPANY,ASSIGN_DATE,RESPONSE_DATE,RESPONSE_DESCRIPTION,SERVICE_DATE,REMEDY_DESCRIPTION,SOLVED_PROBLEM_TYPE
0,183217,2015-12-30 16:58:57,20151566.0,PC,Does not start,pc not lofin trust error show,HIGHER RAM HP PC,OTHERS,WIPRO,NaN,2015-12-30 16:59:33,NaN,2015-12-30 16:59:33,currupt profile reset,OTHER
1,183216,2015-12-30 16:54:48,20150737.0,PRINTER,Other - Please Specify,Printer off line,PC GEN,OTHERS,WIPRO,NaN,2015-12-30 16:55:46,NaN,2015-12-30 16:55:46,Changed setting,OTHER
2,183215,2015-12-30 16:53:41,20151055.0,PC,Does not start,new pc configration and domain add,PC GEN,OTHERS,WIPRO,NaN,2015-12-30 16:54:07,NaN,2015-12-30 16:54:07,config properly,OTHER
3,183214,2015-12-30 16:53:20,20150735.0,PRINTER,Other - Please Specify,Printer off line,PC GEN,OTHERS,WIPRO,NaN,2015-12-30 16:54:09,NaN,2015-12-30 16:54:09,Resolved issue,OTHER
4,183213,2015-12-30 16:51:35,20150329.0,PC,Other - Please Specify,.lst file not open,PC GEN,OTHERS,WIPRO,NaN,2015-12-30 16:52:26,NaN,2015-12-30 16:52:26,Changed setting,OTHER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102559,80663,2010-01-01 10:08:34,20060023.0,OTHER,Other - Please specify,microsoft word latest version - download in la...,software,HP2006,HP2006,NaN,2010-01-01 11:14:26,NaN,2010-01-01 11:14:26,Installed MS office2007.,NaN
102560,80662,2010-01-01 09:56:56,20090000.0,OTHER,Other - Please specify,Internet not working. New connection (shifting...,intranet,HP,NETWORK,NaN,2010-01-01 14:52:22,NaN,2010-03-06 14:48:00,2 NEW LAN PORT INSTALLED DISTANCE 90 METER,NaN
102561,80661,2010-01-01 09:48:04,20090000.0,OTHER,Other - Please specify,There is no network for checking e-mails.,Network connection,OTHERS,CMS,NaN,2010-01-01 09:59:51,NaN,2010-01-01 09:59:51,Not In Our Scope,NaN
102562,80660,2010-01-01 09:43:31,20090000.0,OTHER,Other - Please specify,There is no any network for checking e-mails.,Net connection,OTHERS,NETWORK,NaN,2010-01-01 12:07:53,NaN,2010-01-01 12:07:53,PROBLEM RESOLVED,NaN
102563,80659,2010-01-01 09:35:03,20060811.0,OTHER,Other - Please specify,network not working,PC,HP2006,HP2006,NaN,2010-01-01 14:24:39,NaN,2010-01-01 14:24:39,Cleaned virus & Set system settings.,NaN

In [22]:
df2.dropna(subset=['ID_NO'], inplace=True)

In [25]:
print(df2)

        COMPLAINT_NO      COMPLAINT_DATE       ID_NO FAULTY_EQUIPMENT  \
0             183217 2015-12-30 16:58:57  20151566.0               PC
1             183216 2015-12-30 16:54:48  20150737.0          PRINTER
2             183215 2015-12-30 16:53:41  20151055.0               PC
3             183214 2015-12-30 16:53:20  20150735.0          PRINTER
4             183213 2015-12-30 16:51:35  20150329.0               PC
...              ...                 ...         ...              ...
102559         80663 2010-01-01 10:08:34  20060023.0            OTHER
102560         80662 2010-01-01 09:56:56  20090000.0            OTHER
102561         80661 2010-01-01 09:48:04  20090000.0            OTHER
102562         80660 2010-01-01 09:43:31  20090000.0            OTHER
102563         80659 2010-01-01 09:35:03  20060811.0            OTHER

                  PROBLEM_TYPE  \
0               Does not start
1       Other - Please Specify
2               Does not start
3       Other - Please Specify
4       Other - Please Specify
...                        ...
102559  Other - Please specify
102560  Other - Please specify
102561  Other - Please specify
102562  Other - Please specify
102563  Other - Please specify

                                      PROBLEM_DESCRIPTION   NAME_OF_EQUIPMENT  \
0                          pc not lofin trust error  show    HIGHER RAM HP PC
1                                        Printer off line              PC GEN
2                      new pc configration and domain add              PC GEN
3                                        Printer off line              PC GEN
4                                      .lst file not open              PC GEN
...                                                   ...                 ...
102559  microsoft word latest version - download in la...            software
102560  Internet not working. New connection (shifting...            intranet
102561          There is no network for checking e-mails.  Network connection
102562      There is no any network for checking e-mails.      Net connection
102563                                network not working                  PC

       EQUIPMENT_MAKE SERVICE_COMPANY  ASSIGN_DATE       RESPONSE_DATE  \
0              OTHERS           WIPRO          NaN 2015-12-30 16:59:33
1              OTHERS           WIPRO          NaN 2015-12-30 16:55:46
2              OTHERS           WIPRO          NaN 2015-12-30 16:54:07
3              OTHERS           WIPRO          NaN 2015-12-30 16:54:09
4              OTHERS           WIPRO          NaN 2015-12-30 16:52:26
...               ...             ...          ...                 ...
102559         HP2006          HP2006          NaN 2010-01-01 11:14:26
102560             HP         NETWORK          NaN 2010-01-01 14:52:22
102561         OTHERS             CMS          NaN 2010-01-01 09:59:51
102562         OTHERS         NETWORK          NaN 2010-01-01 12:07:53
102563         HP2006          HP2006          NaN 2010-01-01 14:24:39

        RESPONSE_DESCRIPTION        SERVICE_DATE  \
0                        NaN 2015-12-30 16:59:33
1                        NaN 2015-12-30 16:55:46
2                        NaN 2015-12-30 16:54:07
3                        NaN 2015-12-30 16:54:09
4                        NaN 2015-12-30 16:52:26
...                      ...                 ...
102559                   NaN 2010-01-01 11:14:26
102560                   NaN 2010-03-06 14:48:00
102561                   NaN 2010-01-01 09:59:51
102562                   NaN 2010-01-01 12:07:53
102563                   NaN 2010-01-01 14:24:39

                                REMEDY_DESCRIPTION SOLVED_PROBLEM_TYPE
0                           currupt profile reset                OTHER
1                                  Changed setting               OTHER
2                                  config properly               OTHER
3                                   Resolved issue               OTHER
4                                 Changed setting                OTHER
...                                            ...                 ...
102559                    Installed MS office2007.                 NaN
102560  2 NEW LAN PORT INSTALLED DISTANCE 90 METER                 NaN
102561                            Not In Our Scope                 NaN
102562                            PROBLEM RESOLVED                 NaN
102563        Cleaned virus & Set system settings.                 NaN

[100983 rows x 15 columns]

In [26]:
df2.dropna(subset=['PROBLEM_DESCRIPTION'], inplace=True)

In [27]:
df2

,COMPLAINT_NO,COMPLAINT_DATE,ID_NO,FAULTY_EQUIPMENT,PROBLEM_TYPE,PROBLEM_DESCRIPTION,NAME_OF_EQUIPMENT,EQUIPMENT_MAKE,SERVICE_COMPANY,ASSIGN_DATE,RESPONSE_DATE,RESPONSE_DESCRIPTION,SERVICE_DATE,REMEDY_DESCRIPTION,SOLVED_PROBLEM_TYPE
0,183217,2015-12-30 16:58:57,20151566.0,PC,Does not start,pc not lofin trust error show,HIGHER RAM HP PC,OTHERS,WIPRO,NaN,2015-12-30 16:59:33,NaN,2015-12-30 16:59:33,currupt profile reset,OTHER
1,183216,2015-12-30 16:54:48,20150737.0,PRINTER,Other - Please Specify,Printer off line,PC GEN,OTHERS,WIPRO,NaN,2015-12-30 16:55:46,NaN,2015-12-30 16:55:46,Changed setting,OTHER
2,183215,2015-12-30 16:53:41,20151055.0,PC,Does not start,new pc configration and domain add,PC GEN,OTHERS,WIPRO,NaN,2015-12-30 16:54:07,NaN,2015-12-30 16:54:07,config properly,OTHER
3,183214,2015-12-30 16:53:20,20150735.0,PRINTER,Other - Please Specify,Printer off line,PC GEN,OTHERS,WIPRO,NaN,2015-12-30 16:54:09,NaN,2015-12-30 16:54:09,Resolved issue,OTHER
4,183213,2015-12-30 16:51:35,20150329.0,PC,Other - Please Specify,.lst file not open,PC GEN,OTHERS,WIPRO,NaN,2015-12-30 16:52:26,NaN,2015-12-30 16:52:26,Changed setting,OTHER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102559,80663,2010-01-01 10:08:34,20060023.0,OTHER,Other - Please specify,microsoft word latest version - download in la...,software,HP2006,HP2006,NaN,2010-01-01 11:14:26,NaN,2010-01-01 11:14:26,Installed MS office2007.,NaN
102560,80662,2010-01-01 09:56:56,20090000.0,OTHER,Other - Please specify,Internet not working. New connection (shifting...,intranet,HP,NETWORK,NaN,2010-01-01 14:52:22,NaN,2010-03-06 14:48:00,2 NEW LAN PORT INSTALLED DISTANCE 90 METER,NaN
102561,80661,2010-01-01 09:48:04,20090000.0,OTHER,Other - Please specify,There is no network for checking e-mails.,Network connection,OTHERS,CMS,NaN,2010-01-01 09:59:51,NaN,2010-01-01 09:59:51,Not In Our Scope,NaN
102562,80660,2010-01-01 09:43:31,20090000.0,OTHER,Other - Please specify,There is no any network for checking e-mails.,Net connection,OTHERS,NETWORK,NaN,2010-01-01 12:07:53,NaN,2010-01-01 12:07:53,PROBLEM RESOLVED,NaN
102563,80659,2010-01-01 09:35:03,20060811.0,OTHER,Other - Please specify,network not working,PC,HP2006,HP2006,NaN,2010-01-01 14:24:39,NaN,2010-01-01 14:24:39,Cleaned virus & Set system settings.,NaN

In [28]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 97322 entries, 0 to 102563
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   COMPLAINT_NO          97322 non-null  int64
 1   COMPLAINT_DATE        97322 non-null  datetime64[ns]
 2   ID_NO                 97322 non-null  float64
 3   FAULTY_EQUIPMENT      97322 non-null  object
 4   PROBLEM_TYPE          97322 non-null  object
 5   PROBLEM_DESCRIPTION   97322 non-null  object
 6   NAME_OF_EQUIPMENT     97322 non-null  object
 7   EQUIPMENT_MAKE        97322 non-null  object
 8   SERVICE_COMPANY       97322 non-null  object
 9   ASSIGN_DATE           0 non-null      float64
 10  RESPONSE_DATE         86357 non-null  datetime64[ns]
 11  RESPONSE_DESCRIPTION  0 non-null      float64
 12  SERVICE_DATE          95248 non-null  datetime64[ns]
 13  REMEDY_DESCRIPTION    94611 non-null  object
 14  SOLVED_PROBLEM_TYPE   62212 non-null  object
dtypes: datetime64[ns](3), float64(3), int64(1), object(8)
memory usage: 11.9+ MB

In [29]:
df2.dropna(subset=['REMEDY_DESCRIPTION'], inplace=True)

In [30]:
df2

,COMPLAINT_NO,COMPLAINT_DATE,ID_NO,FAULTY_EQUIPMENT,PROBLEM_TYPE,PROBLEM_DESCRIPTION,NAME_OF_EQUIPMENT,EQUIPMENT_MAKE,SERVICE_COMPANY,ASSIGN_DATE,RESPONSE_DATE,RESPONSE_DESCRIPTION,SERVICE_DATE,REMEDY_DESCRIPTION,SOLVED_PROBLEM_TYPE
0,183217,2015-12-30 16:58:57,20151566.0,PC,Does not start,pc not lofin trust error show,HIGHER RAM HP PC,OTHERS,WIPRO,NaN,2015-12-30 16:59:33,NaN,2015-12-30 16:59:33,currupt profile reset,OTHER
1,183216,2015-12-30 16:54:48,20150737.0,PRINTER,Other - Please Specify,Printer off line,PC GEN,OTHERS,WIPRO,NaN,2015-12-30 16:55:46,NaN,2015-12-30 16:55:46,Changed setting,OTHER
2,183215,2015-12-30 16:53:41,20151055.0,PC,Does not start,new pc configration and domain add,PC GEN,OTHERS,WIPRO,NaN,2015-12-30 16:54:07,NaN,2015-12-30 16:54:07,config properly,OTHER
3,183214,2015-12-30 16:53:20,20150735.0,PRINTER,Other - Please Specify,Printer off line,PC GEN,OTHERS,WIPRO,NaN,2015-12-30 16:54:09,NaN,2015-12-30 16:54:09,Resolved issue,OTHER
4,183213,2015-12-30 16:51:35,20150329.0,PC,Other - Please Specify,.lst file not open,PC GEN,OTHERS,WIPRO,NaN,2015-12-30 16:52:26,NaN,2015-12-30 16:52:26,Changed setting,OTHER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102559,80663,2010-01-01 10:08:34,20060023.0,OTHER,Other - Please specify,microsoft word latest version - download in la...,software,HP2006,HP2006,NaN,2010-01-01 11:14:26,NaN,2010-01-01 11:14:26,Installed MS office2007.,NaN
102560,80662,2010-01-01 09:56:56,20090000.0,OTHER,Other - Please specify,Internet not working. New connection (shifting...,intranet,HP,NETWORK,NaN,2010-01-01 14:52:22,NaN,2010-03-06 14:48:00,2 NEW LAN PORT INSTALLED DISTANCE 90 METER,NaN
102561,80661,2010-01-01 09:48:04,20090000.0,OTHER,Other - Please specify,There is no network for checking e-mails.,Network connection,OTHERS,CMS,NaN,2010-01-01 09:59:51,NaN,2010-01-01 09:59:51,Not In Our Scope,NaN
102562,80660,2010-01-01 09:43:31,20090000.0,OTHER,Other - Please specify,There is no any network for checking e-mails.,Net connection,OTHERS,NETWORK,NaN,2010-01-01 12:07:53,NaN,2010-01-01 12:07:53,PROBLEM RESOLVED,NaN
102563,80659,2010-01-01 09:35:03,20060811.0,OTHER,Other - Please specify,network not working,PC,HP2006,HP2006,NaN,2010-01-01 14:24:39,NaN,2010-01-01 14:24:39,Cleaned virus & Set system settings.,NaN

In [32]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 94611 entries, 0 to 102563
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   COMPLAINT_NO          94611 non-null  int64
 1   COMPLAINT_DATE        94611 non-null  datetime64[ns]
 2   ID_NO                 94611 non-null  float64
 3   FAULTY_EQUIPMENT      94611 non-null  object
 4   PROBLEM_TYPE          94611 non-null  object
 5   PROBLEM_DESCRIPTION   94611 non-null  object
 6   NAME_OF_EQUIPMENT     94611 non-null  object
 7   EQUIPMENT_MAKE        94611 non-null  object
 8   SERVICE_COMPANY       94611 non-null  object
 9   ASSIGN_DATE           0 non-null      float64
 10  RESPONSE_DATE         85633 non-null  datetime64[ns]
 11  RESPONSE_DESCRIPTION  0 non-null      float64
 12  SERVICE_DATE          94610 non-null  datetime64[ns]
 13  REMEDY_DESCRIPTION    94611 non-null  object
 14  SOLVED_PROBLEM_TYPE   61661 non-null  object
dtypes: datetime64[ns](3), float64(3), int64(1), object(8)
memory usage: 11.5+ MB